# Generated by Django 4.2.1 on 2023-08-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted_on'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
