# Generated by Django 4.2.1 on 2023-09-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_post_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_views',
            field=models.IntegerField(default=1),
        ),
    ]
